import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const students = [
  {
    name: 'Ana Clara Mendes',
    grade: '3º Ano EM',
    school: 'Colégio Estadual João XXIII',
    responsibleName: 'Carla Mendes',
    responsiblePhone: '11991234567',
    billingType: 'MONTHLY' as const,
    monthlyFee: 480,
    currentLevel: 'Intermediário',
    strengths: 'Boa interpretação de texto, facilidade com redação',
    areasToImprove: 'Matemática, especialmente funções e trigonometria',
    goals: 'Aprovação no ENEM com nota acima de 700',
    schedulePreferences: [{ dayOfWeek: 1, startTime: '08:00', endTime: '09:30' }],
  },
  {
    name: 'Bruno Ferreira Lima',
    grade: '2º Ano EM',
    school: 'Escola Particular São Lucas',
    responsibleName: 'Paulo Lima',
    responsiblePhone: '11982345678',
    billingType: 'MONTHLY' as const,
    monthlyFee: 550,
    currentLevel: 'Básico',
    strengths: 'Dedicado, persistente, boa memória',
    areasToImprove: 'Química orgânica e física mecânica',
    goals: 'Melhorar média geral para 7.0',
    schedulePreferences: [{ dayOfWeek: 2, startTime: '14:00', endTime: '15:30' }],
  },
  {
    name: 'Camila Souza Rodrigues',
    grade: '9º Ano EF',
    school: 'Escola Municipal Dom Bosco',
    responsibleName: 'Fernanda Rodrigues',
    responsiblePhone: '11973456789',
    billingType: 'HOURLY' as const,
    hourlyRate: 90,
    currentLevel: 'Intermediário',
    strengths: 'Curiosidade, participa ativamente das aulas',
    areasToImprove: 'Álgebra e equações do 2º grau',
    goals: 'Passar de ano com boas notas em Matemática',
    schedulePreferences: [{ dayOfWeek: 3, startTime: '16:00', endTime: '17:30' }],
  },
  {
    name: 'Diego Alves Costa',
    grade: '1º Ano EM',
    school: 'Colégio Técnico Federal',
    responsibleName: 'Roberto Costa',
    responsiblePhone: '11964567890',
    billingType: 'MONTHLY' as const,
    monthlyFee: 500,
    currentLevel: 'Básico',
    strengths: 'Raciocínio lógico, boa base em informática',
    areasToImprove: 'Português, produção textual e gramática',
    goals: 'Melhorar redação para vestibular',
    schedulePreferences: [{ dayOfWeek: 4, startTime: '18:00', endTime: '19:30' }],
  },
  {
    name: 'Eduarda Martins Pereira',
    grade: '3º Ano EM',
    school: 'Colégio Particular Vanguarda',
    responsibleName: 'Silvia Pereira',
    responsiblePhone: '11955678901',
    billingType: 'MONTHLY' as const,
    monthlyFee: 620,
    currentLevel: 'Avançado',
    strengths: 'Excelente em Biologia e Química',
    areasToImprove: 'Física moderna e cálculo diferencial introdutório',
    goals: 'Aprovação em medicina na USP',
    schedulePreferences: [{ dayOfWeek: 5, startTime: '09:00', endTime: '10:30' }],
  },
  {
    name: 'Felipe Nascimento Gomes',
    grade: '8º Ano EF',
    school: 'Escola Municipal Santos Dumont',
    responsibleName: 'Marcos Gomes',
    responsiblePhone: '11946789012',
    billingType: 'MONTHLY' as const,
    monthlyFee: 380,
    currentLevel: 'Básico',
    strengths: 'Criativo, gosta de ciências',
    areasToImprove: 'Interpretação de texto e operações matemáticas',
    goals: 'Recuperar notas e passar de ano',
    schedulePreferences: [{ dayOfWeek: 1, startTime: '10:00', endTime: '11:30' }],
  },
  {
    name: 'Gabriela Oliveira Santos',
    grade: '2º Ano EM',
    school: 'Colégio Estadual Tiradentes',
    responsibleName: 'Luciana Santos',
    responsiblePhone: '11937890123',
    billingType: 'HOURLY' as const,
    hourlyRate: 100,
    currentLevel: 'Intermediário',
    strengths: 'Determinada, boa em história e geografia',
    areasToImprove: 'Matemática financeira e probabilidade',
    goals: 'Conseguir bolsa no ProUni',
    schedulePreferences: [{ dayOfWeek: 2, startTime: '08:00', endTime: '09:30' }],
  },
  {
    name: 'Henrique Carvalho Dias',
    grade: '3º Ano EM',
    school: 'Escola Particular Anglo',
    responsibleName: 'André Dias',
    responsiblePhone: '11928901234',
    billingType: 'MONTHLY' as const,
    monthlyFee: 700,
    currentLevel: 'Avançado',
    strengths: 'Excelente em Física e Matemática',
    areasToImprove: 'Língua Inglesa e atualidades para redação',
    goals: 'Aprovação em Engenharia na Unicamp',
    schedulePreferences: [{ dayOfWeek: 3, startTime: '19:00', endTime: '20:30' }],
  },
  {
    name: 'Isabela Torres Vieira',
    grade: '1º Ano EM',
    school: 'Colégio Particular Notre Dame',
    responsibleName: 'Patricia Vieira',
    responsiblePhone: '11919012345',
    billingType: 'MONTHLY' as const,
    monthlyFee: 520,
    currentLevel: 'Intermediário',
    strengths: 'Organizada, comprometida com os estudos',
    areasToImprove: 'Química e biologia celular',
    goals: 'Manter média acima de 8.0',
    schedulePreferences: [{ dayOfWeek: 4, startTime: '14:00', endTime: '15:30' }],
  },
  {
    name: 'João Pedro Ribeiro',
    grade: '9º Ano EF',
    school: 'Escola Estadual Professor Anísio',
    responsibleName: 'Claudia Ribeiro',
    responsiblePhone: '11910123456',
    billingType: 'MONTHLY' as const,
    monthlyFee: 350,
    currentLevel: 'Básico',
    strengths: 'Curioso, faz muitas perguntas',
    areasToImprove: 'Português e matemática elementar',
    goals: 'Aprovação no ensino médio técnico',
    schedulePreferences: [{ dayOfWeek: 5, startTime: '16:00', endTime: '17:30' }],
  },
  {
    name: 'Karen Almeida Cruz',
    grade: '2º Ano EM',
    school: 'Colégio Particular Objetivo',
    responsibleName: 'Renata Cruz',
    responsiblePhone: '11901234567',
    billingType: 'HOURLY' as const,
    hourlyRate: 110,
    currentLevel: 'Avançado',
    strengths: 'Excelente raciocínio matemático, rápida aprendizagem',
    areasToImprove: 'Redação e interpretação de textos filosóficos',
    goals: 'Competir em olimpíadas de matemática',
    schedulePreferences: [{ dayOfWeek: 6, startTime: '09:00', endTime: '10:30' }],
  },
  {
    name: 'Lucas Monteiro Pinto',
    grade: '3º Ano EM',
    school: 'Colégio Estadual Rui Barbosa',
    responsibleName: 'Gustavo Pinto',
    responsiblePhone: '11892345678',
    billingType: 'MONTHLY' as const,
    monthlyFee: 460,
    currentLevel: 'Intermediário',
    strengths: 'Esforçado, boa base em exatas',
    areasToImprove: 'Física ondulatória e eletromagnetismo',
    goals: 'ENEM acima de 650 para curso de TI',
    schedulePreferences: [{ dayOfWeek: 1, startTime: '19:00', endTime: '20:30' }],
  },
  {
    name: 'Mariana Freitas Barbosa',
    grade: '1º Ano EM',
    school: 'Colégio Particular Sigma',
    responsibleName: 'Juliana Barbosa',
    responsiblePhone: '11883456789',
    billingType: 'MONTHLY' as const,
    monthlyFee: 530,
    currentLevel: 'Básico',
    strengths: 'Criativa, gosta de arte e literatura',
    areasToImprove: 'Álgebra e geometria analítica',
    goals: 'Aprovar em publicidade na PUC',
    schedulePreferences: [{ dayOfWeek: 2, startTime: '16:00', endTime: '17:30' }],
  },
  {
    name: 'Nicolas Araújo Moreira',
    grade: '8º Ano EF',
    school: 'Escola Municipal Castro Alves',
    responsibleName: 'Tatiana Moreira',
    responsiblePhone: '11874567890',
    billingType: 'MONTHLY' as const,
    monthlyFee: 400,
    currentLevel: 'Básico',
    strengths: 'Muito inteligente, aprende rápido quando motivado',
    areasToImprove: 'Foco e organização, português e ciências',
    goals: 'Passar de ano sem recuperação',
    schedulePreferences: [{ dayOfWeek: 3, startTime: '14:00', endTime: '15:30' }],
  },
  {
    name: 'Olivia Campos Neves',
    grade: '3º Ano EM',
    school: 'Colégio Particular Eliezer',
    responsibleName: 'Miriam Neves',
    responsiblePhone: '11865678901',
    billingType: 'MONTHLY' as const,
    monthlyFee: 580,
    currentLevel: 'Avançado',
    strengths: 'Excelente em biologia, Química e redação',
    areasToImprove: 'Física e matemática para vestibular de medicina',
    goals: 'Aprovação em Medicina na FMUSP',
    schedulePreferences: [{ dayOfWeek: 4, startTime: '08:00', endTime: '09:30' }],
  },
  {
    name: 'Pedro Henrique Lopes',
    grade: '2º Ano EM',
    school: 'Colégio Estadual Getúlio Vargas',
    responsibleName: 'Wagner Lopes',
    responsiblePhone: '11856789012',
    billingType: 'HOURLY' as const,
    hourlyRate: 95,
    currentLevel: 'Intermediário',
    strengths: 'Boa desenvoltura oral, curioso em ciências da natureza',
    areasToImprove: 'Matemática e gramática portuguesa',
    goals: 'Melhorar notas para não reprovar',
    schedulePreferences: [{ dayOfWeek: 5, startTime: '14:00', endTime: '15:30' }],
  },
  {
    name: 'Rafaela Duarte Cunha',
    grade: '9º Ano EF',
    school: 'Escola Particular Adventista',
    responsibleName: 'Beatriz Cunha',
    responsiblePhone: '11847890123',
    billingType: 'MONTHLY' as const,
    monthlyFee: 420,
    currentLevel: 'Intermediário',
    strengths: 'Disciplinada, boa memória, esforçada',
    areasToImprove: 'Matemática: geometria e sistemas lineares',
    goals: 'Aprovação em escola técnica estadual',
    schedulePreferences: [{ dayOfWeek: 6, startTime: '10:00', endTime: '11:30' }],
  },
  {
    name: 'Samuel Rocha Teixeira',
    grade: '1º Ano EM',
    school: 'Colégio Estadual Oswaldo Cruz',
    responsibleName: 'Vera Teixeira',
    responsiblePhone: '11838901234',
    billingType: 'MONTHLY' as const,
    monthlyFee: 450,
    currentLevel: 'Básico',
    strengths: 'Persistente, boa relação com tecnologia',
    areasToImprove: 'Todas as disciplinas — aluno recém-transferido',
    goals: 'Adaptação ao novo colégio e recuperação do conteúdo',
    schedulePreferences: [{ dayOfWeek: 1, startTime: '16:00', endTime: '17:30' }],
  },
  {
    name: 'Thais Correia Figueiredo',
    grade: '3º Ano EM',
    school: 'Colégio Particular Leonardo da Vinci',
    responsibleName: 'Ana Figueiredo',
    responsiblePhone: '11829012345',
    billingType: 'MONTHLY' as const,
    monthlyFee: 650,
    currentLevel: 'Avançado',
    strengths: 'Fluente em inglês, excelente em redação e humanas',
    areasToImprove: 'Química e física para completar nota no ENEM',
    goals: 'Nota 900+ no ENEM para Direito na USP',
    schedulePreferences: [{ dayOfWeek: 2, startTime: '19:00', endTime: '20:30' }],
  },
  {
    name: 'Vitor Hugo Azevedo',
    grade: '2º Ano EM',
    school: 'Colégio Estadual Dom Pedro II',
    responsibleName: 'Ricardo Azevedo',
    responsiblePhone: '11820123456',
    billingType: 'HOURLY' as const,
    hourlyRate: 85,
    currentLevel: 'Intermediário',
    strengths: 'Boa base matemática, gosta de física experimental',
    areasToImprove: 'Química e biologia, além de redação argumentativa',
    goals: 'Ingressar em Engenharia Mecânica',
    schedulePreferences: [{ dayOfWeek: 3, startTime: '18:00', endTime: '19:30' }],
  },
];

async function main() {
  const user = await prisma.user.findFirst();
  if (!user) {
    console.error('Nenhum usuário encontrado. Faça login na aplicação primeiro.');
    process.exit(1);
  }

  console.log(`Cadastrando 20 alunos para o usuário: ${user.name} (${user.email})`);

  let created = 0;
  for (const student of students) {
    const { schedulePreferences, ...studentData } = student;
    await prisma.student.create({
      data: {
        ...studentData,
        userId: user.id,
        schedulePreferences: {
          create: schedulePreferences,
        },
        shareToken: {
          create: {},
        },
      },
    });
    created++;
    console.log(`  ✓ ${student.name}`);
  }

  console.log(`\n${created} alunos cadastrados com sucesso!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
